version: '3.8'
name: 'coffee_bot'
services:
  coffee-bot-mongo-prod:
    image: mongo:latest
    container_name: coffee_bot_mongo_prod
    volumes:
      - 'mongo-data:/data/db'
      - './init:/docker-entrypoint-initdb.d'
    ports:
      - "27017:27017"
    env_file:
      - .env.production
    networks:
      - coffee_bot_network

  coffee-bot:
    depends_on:
      - coffee-bot-mongo-prod
    image: ghcr.io/szabolcs-dekany/coffee-bot:latest
    container_name: coffee_bot_prod
    networks:
      - coffee_bot_network
    env_file:
      - .env.production

volumes:
  mongo-data:

networks:
  coffee_bot_network: